//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NutriApp5.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class COMERCIOS
    {
        public COMERCIOS()
        {
            this.BUSQUEDAXCOMERCIOS = new HashSet<BUSQUEDAXCOMERCIOS>();
            this.PRODUCTOSXCOMERCIO = new HashSet<PRODUCTOSXCOMERCIO>();
        }
        [Key]
        public int ID_COMERCIO { get; set; }
        public Nullable<decimal> ID_TIPO { get; set; }
        public Nullable<int> ID_USUARIO { get; set; }
        public string NOMBRE { get; set; }
        public Nullable<decimal> LATITUD { get; set; }
        public Nullable<decimal> LONGUITUD { get; set; }
        public Nullable<decimal> TELEFONO { get; set; }
        public string CORREO { get; set; }
    
        public virtual ICollection<BUSQUEDAXCOMERCIOS> BUSQUEDAXCOMERCIOS { get; set; }
        public virtual ICollection<PRODUCTOSXCOMERCIO> PRODUCTOSXCOMERCIO { get; set; }
        public virtual TIPO_COMERCIO TIPO_COMERCIO { get; set; }
    }
}
