//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NutriApp5.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class PRODUCTOS
    {
        public PRODUCTOS()
        {
            this.BUSQUEDAXPRODUCTOS = new HashSet<BUSQUEDAXPRODUCTOS>();
            this.PRODUCTOSXCOMERCIO = new HashSet<PRODUCTOSXCOMERCIO>();
        }
        [Key]
        public int ID_PRODUCTO { get; set; }
        public Nullable<decimal> ID_TIPO { get; set; }
        public Nullable<decimal> TIPO { get; set; }
        public string NOMBRE { get; set; }
        public string INFORMACION_ADICIONAL { get; set; }
    
        public virtual ICollection<BUSQUEDAXPRODUCTOS> BUSQUEDAXPRODUCTOS { get; set; }
        public virtual ICollection<PRODUCTOSXCOMERCIO> PRODUCTOSXCOMERCIO { get; set; }
        public virtual TIPO_PRODUCTO TIPO_PRODUCTO { get; set; }
    }
}
