//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nutriApp3.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class BITACORA_USUARIOS
    {
        [Key]
        public int ID_BITACORA { get; set; }
        public Nullable<int> ID_USR_IMPLICADO { get; set; }
        public string CORREO_ANTERIOR { get; set; }
        public string NOMBRE_ANTERIOR { get; set; }
        public string APELLIDO_ANTERIOR { get; set; }
        public Nullable<decimal> ID_ROL_ANTERIOR { get; set; }
        public Nullable<System.DateTime> FECHA_MODIFICACION { get; set; }
        public string ACCION_REALIZADA { get; set; }
    }
}
