//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nutriApp3.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class BITACORA_NOTICIAS
    {
        [Key]   
        public int ID_BITACORA { get; set; }
        public Nullable<int> ID_USR_RESPONSABLE { get; set; }
        public Nullable<System.DateTime> FECHA_MODIFICACION { get; set; }
        public string ACCION_REALIZADA { get; set; }
    }
}
