//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nutriApp3.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class PRODUCTOS
    {
        public PRODUCTOS()
        {
            this.BUSQUEDAS = new HashSet<BUSQUEDAS>();
            this.COMERCIOS = new HashSet<COMERCIOS>();
        }
        [Key]
        public int ID_PRODUCTO { get; set; }
        public Nullable<decimal> ID_TIPO { get; set; }
        public Nullable<decimal> TIPO { get; set; }
        public string NOMBRE { get; set; }
        public string INFORMACION_ADICIONAL { get; set; }
    
        public virtual TIPO_PRODUCTO TIPO_PRODUCTO { get; set; }
        public virtual ICollection<BUSQUEDAS> BUSQUEDAS { get; set; }
        public virtual ICollection<COMERCIOS> COMERCIOS { get; set; }
    }
}
