//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NutriApp5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BUSQUEDAXPRODUCTOS
    {
        public int ID { get; set; }
        public int ID_BUSQUEDA { get; set; }
        public int ID_PRODUCTO { get; set; }
    
        public virtual BUSQUEDAS BUSQUEDAS { get; set; }
        public virtual PRODUCTOS PRODUCTOS { get; set; }
    }
}
