//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NutriApp5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_INFORMACION
    {
        public TIPO_INFORMACION()
        {
            this.NOTICIAS = new HashSet<NOTICIAS>();
        }
    
        public decimal ID_TIPO { get; set; }
        public string NOMBRE { get; set; }
    
        public virtual ICollection<NOTICIAS> NOTICIAS { get; set; }
    }
}
