//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NutriApp5.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class COMERCIOS
    {
        public COMERCIOS()
        {
            this.BUSQUEDAXCOMERCIOS = new HashSet<BUSQUEDAXCOMERCIOS>();
            this.PRODUCTOSXCOMERCIO = new HashSet<PRODUCTOSXCOMERCIO>();
        }
        [Key]
        public int ID_COMERCIO { get; set; }
        public Nullable<decimal> ID_TIPO { get; set; }
        public Nullable<int> ID_USUARIO { get; set; }
        public string NOMBRE { get; set; }
      //  [RegularExpression(@"\A\d+(\.\d{2,16})?\Z", ErrorMessage = "Please enter a numeric value with up to two decimal places.")]
        public Double LATITUD { get; set; }
       // [RegularExpression(@"\A\d+(\.\d{2,16})?\Z", ErrorMessage = "Please enter a numeric value with up to two decimal places.")]
        public Double LONGUITUD { get; set; }
        public Nullable<decimal> TELEFONO { get; set; }
        public string CORREO { get; set; }

        public IEnumerable<PRODUCTOS> PRODUCTOS { get; set; }
        
    
        public virtual ICollection<BUSQUEDAXCOMERCIOS> BUSQUEDAXCOMERCIOS { get; set; }
        public virtual ICollection<PRODUCTOSXCOMERCIO> PRODUCTOSXCOMERCIO { get; set; }
        public virtual TIPO_COMERCIO TIPO_COMERCIO { get; set; }
    }

    public class createEditComercios
    {
        public int ID_COMERCIO { get; set; }
        public Nullable<decimal> ID_TIPO { get; set; }
       
        [Required]
        public string NOMBRE { get; set; }
        [Required]
       // [RegularExpression(@"\A\d+(\.\d{2,16})?\Z", ErrorMessage = "Please enter a numeric value with up to two decimal places.")]
        public Double LATITUD { get; set; }
        [Required]
       // [RegularExpression(@"\A\d+(\.\d{2,16})?\Z", ErrorMessage = "Please enter a numeric value with up to two decimal places.")]
        public Double LONGUITUD { get; set; }
        [Required]
       
        public Nullable<decimal> TELEFONO { get; set; }
        [Required]
        [EmailAddress] 
        public string CORREO { get; set; }

       
        public Nullable<int> selectedUser { get; set; }
        public IEnumerable<System.Web.Mvc.SelectListItem> AllUSERS { get; set; }

        public IEnumerable<int> SelectedPRODUCTOS { get; set; }
        public IEnumerable<System.Web.Mvc.SelectListItem> AllPRODUCTOS { get; set; }
    }
}
