//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NutriApp5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONDICION
    {
        public CONDICION()
        {
            this.NOTICIASXCONDICION = new HashSet<NOTICIASXCONDICION>();
            this.USUARIOXCONDICION = new HashSet<USUARIOXCONDICION>();
        }
    
        public decimal ID_CONDICION { get; set; }
        public string NOMBRE { get; set; }
        public string INFORMACION_CONDICION { get; set; }
    
        public virtual ICollection<NOTICIASXCONDICION> NOTICIASXCONDICION { get; set; }
        public virtual ICollection<USUARIOXCONDICION> USUARIOXCONDICION { get; set; }
    }
}
