//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NutriApp5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOTICIAS
    {
        public NOTICIAS()
        {
            this.NOTICIASXCONDICION = new HashSet<NOTICIASXCONDICION>();
        }
    
        public int ID_NOTICIA { get; set; }
        public Nullable<int> ID_USUARIO_CREADOR { get; set; }
        public Nullable<decimal> ID_TIPO_INFORMACION { get; set; }
        public string TITULO { get; set; }
        public string CUERPO_NOTICIA { get; set; }
    
        public virtual USUARIOS USUARIOS { get; set; }
        public virtual ICollection<NOTICIASXCONDICION> NOTICIASXCONDICION { get; set; }
        public virtual TIPO_INFORMACION TIPO_INFORMACION { get; set; }
    }
}
