//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NutriApp5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_PRODUCTO
    {
        public TIPO_PRODUCTO()
        {
            this.PRODUCTOS = new HashSet<PRODUCTOS>();
        }
    
        public decimal ID_TIPO { get; set; }
        public string NOMBRE { get; set; }
    
        public virtual ICollection<PRODUCTOS> PRODUCTOS { get; set; }
    }
}
