//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NutriApp5.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class TIPO_COMERCIO
    {
        public TIPO_COMERCIO()
        {
            this.COMERCIOS = new HashSet<COMERCIOS>();
        }
        [Key]
        public decimal ID_TIPO { get; set; }
        public string NOMBRE { get; set; }
    
        public virtual ICollection<COMERCIOS> COMERCIOS { get; set; }
    }
}
