//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NutriApp5.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class USUARIOS
    {
        private readonly IROLESXUSUARIORepository rolesXusuarioRepository = new ROLESXUSUARIORepository();
        public USUARIOS()
        {
            this.BUSQUEDAS = new HashSet<BUSQUEDAS>();
            this.NOTICIAS = new HashSet<NOTICIAS>();
            this.ROLESXUSUARIO = new HashSet<ROLESXUSUARIO>();
            this.USUARIOXCONDICION = new HashSet<USUARIOXCONDICION>();
        }
        [Key]
        public int ID_USUARIO { get; set; }
        public string NOMBRE { get; set; }
        public string APELLIDO { get; set; }
        public string CORREO { get; set; }
        public string CONTRASENA { get; set; }
    
        public virtual ICollection<BUSQUEDAS> BUSQUEDAS { get; set; }
        public virtual ICollection<NOTICIAS> NOTICIAS { get; set; }
        public virtual ICollection<ROLESXUSUARIO> ROLESXUSUARIO { get; set; }
        public virtual ICollection<USUARIOXCONDICION> USUARIOXCONDICION { get; set; }

        public virtual ICollection<ROLES> ROLES { get; set; }
        public virtual ICollection<CONDICION> CONDICIONES { get; set; }

        private void cargaRolesUsuario()
        {
           
        }
    }
    public class ModeloLogin
    {
        [Required]
        [Display(Name = "Nombre de usuario")]
        public string UserName { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Contraseña")]
        public string Password { get; set; }
    }

    public class ModeloRegistro
    {
        [Required]
        [Display(Name = "Nombre")]
        public string NOMBRE { get; set; }

        [Required]
        [Display(Name = "Apellidos")]
        public string APELLIDO { get; set; }

        [Required]
        [EmailAddress]
        [StringLength(100, ErrorMessage = "Formato: email@domain.domain", MinimumLength = 6)]
        [Display(Name = "Correo Electrónico")]
        public string CORREO { get; set; }

        public IEnumerable<decimal> SelectedROLES { get; set; }
        public IEnumerable<System.Web.Mvc.SelectListItem> AllROLES { get; set; }

        public IEnumerable<decimal> SelectedCONDICIONES { get; set; }
        public IEnumerable<System.Web.Mvc.SelectListItem> AllCONDICIONES { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "El número de caracteres de {0} debe ser al menos {2}.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "Contraseña")]
        public string password { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirmar contraseña")]
        [Compare("password", ErrorMessage = "La contraseña y la contraseña de confirmación no coinciden.")]
        public string ConfirmPassword { get; set; }
    }
    public class editUserViewModel
    {
        public int ID_USUARIO { get; set; }
        public string NOMBRE { get; set; }
        public string APELLIDO { get; set; }
        [EmailAddress]
        public string CORREO { get; set; }
        public string CONTRASENA { get; set; }

        public IEnumerable<decimal> SelectedROLES { get; set; }
        public IEnumerable<System.Web.Mvc.SelectListItem> AllROLES { get; set; }

        public IEnumerable<decimal> SelectedCONDICIONES { get; set; }
        public IEnumerable<System.Web.Mvc.SelectListItem> AllCONDICIONES { get; set; }

    }
}
