//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NutriApp5.Models
{
    using System;
    using System.Collections.Generic;

    using NutriApp5.Models.Usuarios.Roles;
    
    public partial class USUARIOS
    {
        public USUARIOS()
        {
            this.BUSQUEDAS = new HashSet<BUSQUEDAS>();
            this.NOTICIAS = new HashSet<NOTICIAS>();
            this.ROLESXUSUARIO = new HashSet<ROLESXUSUARIO>();
            this.USUARIOXCONDICION = new HashSet<USUARIOXCONDICION>();

            this.RolesUsuario = new List<RolUsuario>();
        }
        private readonly USUARIOSRepository usuariosRepository = new USUARIOSRepository();
       
        public int ID_USUARIO { get; set; }
        public string NOMBRE { get; set; }
        public string APELLIDO { get; set; }
        public string CORREO { get; set; }
        public string CONTRASENA { get; set; }
    
        public virtual ICollection<BUSQUEDAS> BUSQUEDAS { get; set; }
        public virtual ICollection<NOTICIAS> NOTICIAS { get; set; }
        public virtual ICollection<ROLESXUSUARIO> ROLESXUSUARIO { get; set; }
        public virtual ICollection<USUARIOXCONDICION> USUARIOXCONDICION { get; set; }

        public ICollection<RolUsuario> RolesUsuario { get; set; }

        public virtual ICollection<ROLES> ROLES { get; set; }
        public virtual ICollection<CONDICION> CONDICIONES { get; set; }

        public void createRoles()
        {
            ICollection<ROLES> rolesUsuario = usuariosRepository.getUserRoles(this.ID_USUARIO);
            foreach (var rol in rolesUsuario)
            {
                switch (rol.ID_ROL.ToString())
                {
                    case "0":
                        this.RolesUsuario.Add(new AdministradorPlataforma());
                        break;
                    case "1":
                        this.RolesUsuario.Add(new AdministradorComercio());
                        break;
                    case "2":
                        this.RolesUsuario.Add(new Partner());
                        break;
                    case "3":
                        this.RolesUsuario.Add(new Comun());
                        break;
                }
            }
        }
    }
}
